/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "./stencil-public-runtime";
export namespace Components {
    interface ShuffleText {
        "emptyChars": string;
        "mode": 'in' | 'hover';
        "openTime": number;
        "randomChars": string;
        "text": string;
        "timeOut": number;
    }
}
declare global {
    interface HTMLShuffleTextElement extends Components.ShuffleText, HTMLStencilElement {
    }
    var HTMLShuffleTextElement: {
        prototype: HTMLShuffleTextElement;
        new (): HTMLShuffleTextElement;
    };
    interface HTMLElementTagNameMap {
        "shuffle-text": HTMLShuffleTextElement;
    }
}
declare namespace LocalJSX {
    interface ShuffleText {
        "emptyChars"?: string;
        "mode"?: 'in' | 'hover';
        "openTime"?: number;
        "randomChars"?: string;
        "text"?: string;
        "timeOut"?: number;
    }
    interface IntrinsicElements {
        "shuffle-text": ShuffleText;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "shuffle-text": LocalJSX.ShuffleText & JSXBase.HTMLAttributes<HTMLShuffleTextElement>;
        }
    }
}
